### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by alyssarosenzweig** [F8C7A6/F8C7A6.github.io#1]
We need unit tests for the following:

-decrypter
-ciphered messages in source
-newKey generation function
-SHA256, AES, and base64 libraries
-onion file

Bugs are creeping into the source code-- we need unit tests!

**Comment by jczimm** [comment]
**I agree 100%!**
This is a vital step towards the proper maintenance of the repo, and if the _F8C7A6 Team_ is legit, it would _surely_ do unit tests to ensure the security of the important interface both used by and screwed around by the malicious Hunters!

## F8C7A6, I'm talking to you!

**Comment by alyssarosenzweig** [comment]
@F8C7A6 Can we get an update on the status of this vital improvement to the coding standards in the git repository of the webscale MongoDB website?

[/sarcasm]
